export interface CropTechnicalSheetData {
  id: string;
  crop_key: string;
  name_fr: string;
  category: string;
  cycle_days_min: number;
  cycle_days_max: number;
  climate_zones: string[];
  seasons: string[];
  npk_needs: { N: number; P: number; K: number };
  water_needs_mm: number;
  common_pests: string[];
  common_diseases: string[];
  recommended_varieties: string[];
  yield_potential_t_ha: number;
  notes: string;
  iconName: string;
}

export const BURKINA_ALL_CROPS_TECHNICAL_SHEETS: CropTechnicalSheetData[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // 1. CÉRÉALES
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "sheet-mais",
    crop_key: "mais",
    name_fr: "Maïs (Zea mays)",
    category: "Céréales",
    cycle_days_min: 80,
    cycle_days_max: 120,
    climate_zones: ["Soudanien", "Soudano-sahélien", "Guinéen"],
    seasons: ["Hivernage (Pluviale)", "Contre-saison irriguée"],
    npk_needs: { N: 100, P: 50, K: 50 },
    water_needs_mm: 550,
    common_pests: ["Chenille légionnaire d'automne (Spodoptera frugiperda)", "Foreurs de tiges (Sesamia)", "Charançons des stocks"],
    common_diseases: ["Helminthosporiose", "Rouille commune", "Strie du maïs (MSV)"],
    recommended_varieties: ["Barkas", "Bondofa", "Kabras", "Espoir (QPM)", "FBC6", "Massango"],
    yield_potential_t_ha: 5.5,
    notes: "Exige un apport fractionné en urée (au semis/démariage puis au tallage/montaison). Forte sensibilité au déficit hydrique pendant la floraison.",
    iconName: "wheat",
  },
  {
    id: "sheet-riz",
    crop_key: "riz_pluvial",
    name_fr: "Riz pluvial & Bas-fond (Oryza sativa / glaberrima)",
    category: "Céréales",
    cycle_days_min: 90,
    cycle_days_max: 135,
    climate_zones: ["Soudanien", "Soudano-sahélien", "Bas-fonds aménagés"],
    seasons: ["Hivernage", "Contre-saison irriguée"],
    npk_needs: { N: 120, P: 60, K: 40 },
    water_needs_mm: 800,
    common_pests: ["Cécidomyie du riz (Orseolia oryzivora)", "Foreurs de tiges (Chilo)", "Oiseaux granivores"],
    common_diseases: ["Pyriculariose (Magnaporthe oryzae)", "Panachure jaune du riz (RYMV)", "Flétrissement bactérien"],
    recommended_varieties: ["TS2", "FKR 19", "FKR 62N (NERICA 4)", "FKR 64", "Orylux 6", "NERICA 6"],
    yield_potential_t_ha: 6.0,
    notes: "Nivellement rigoureux requis pour l'irrigation et la maîtrise de la lame d'eau. Désherbage précoce crucial les 30 premiers jours.",
    iconName: "wheat",
  },
  {
    id: "sheet-sorgho",
    crop_key: "sorgho_blanc",
    name_fr: "Sorgho blanc (Sorghum bicolor)",
    category: "Céréales",
    cycle_days_min: 90,
    cycle_days_max: 140,
    climate_zones: ["Sahel", "Soudano-sahélien", "Soudanien"],
    seasons: ["Hivernage (Pluviale)"],
    npk_needs: { N: 60, P: 30, K: 30 },
    water_needs_mm: 400,
    common_pests: ["Punaise des panicules", "Cécidomyie du sorgho", "Striga hermonthica (adventice parasite)"],
    common_diseases: ["Anthracnose", "Charbon de la panicule", "Ergot du sorgho"],
    recommended_varieties: ["Framida (tolérante Striga)", "Sariaso 11", "Kapelga", "Soubatimi", "CSM 63-E"],
    yield_potential_t_ha: 3.5,
    notes: "Grande tolérance à la sécheresse et aux sols pauvres. Clé de voûte de la résilience céréalière sahélienne.",
    iconName: "wheat",
  },
  {
    id: "sheet-sorgho-rouge",
    crop_key: "sorgho_rouge",
    name_fr: "Sorgho rouge / Dolo (Sorghum bicolor var. rouge)",
    category: "Céréales",
    cycle_days_min: 100,
    cycle_days_max: 145,
    climate_zones: ["Soudano-sahélien", "Soudanien"],
    seasons: ["Hivernage"],
    npk_needs: { N: 60, P: 30, K: 30 },
    water_needs_mm: 420,
    common_pests: ["Foreurs de tige (Busseola fusca)", "Punaise des graines", "Striga hermonthica"],
    common_diseases: ["Anthracnose foliaire", "Mildiou du sorgho", "Charbon nu"],
    recommended_varieties: ["Gnofing", "Sorgho rouge local Farako-Bâ"],
    yield_potential_t_ha: 3.0,
    notes: "Spéculation très demandée par les brasseries artisanales locales de dolo. Forte teneur en anthocyanes protecteurs.",
    iconName: "wheat",
  },
  {
    id: "sheet-mil",
    crop_key: "mil",
    name_fr: "Mil pénicillaire (Pennisetum glaucum)",
    category: "Céréales",
    cycle_days_min: 75,
    cycle_days_max: 110,
    climate_zones: ["Sahel", "Soudano-sahélien"],
    seasons: ["Hivernage"],
    npk_needs: { N: 40, P: 20, K: 20 },
    water_needs_mm: 350,
    common_pests: ["Mineuse de l'épi (Heliocheilus albipunctella)", "Sauteriaux", "Oiseaux quelea"],
    common_diseases: ["Mildiou (Sclerospora graminicola)", "Charbon", "Rouille"],
    recommended_varieties: ["IKMP 5", "Misari 1", "SOSAT C88", "Toroniou"],
    yield_potential_t_ha: 2.5,
    notes: "Extrêmement rustique, adapté aux sols sableux sahéliens. Idéal en association avec le niébé.",
    iconName: "wheat",
  },
  {
    id: "sheet-fonio",
    crop_key: "fonio",
    name_fr: "Fonio blanc (Digitaria exilis)",
    category: "Céréales",
    cycle_days_min: 65,
    cycle_days_max: 95,
    climate_zones: ["Soudanien", "Guinéen", "Cascades"],
    seasons: ["Hivernage"],
    npk_needs: { N: 30, P: 20, K: 20 },
    water_needs_mm: 300,
    common_pests: ["Oiseaux granivores", "Pucerons des graminées"],
    common_diseases: ["Charbon du fonio", "Helminthosporiose"],
    recommended_varieties: ["Fonio précoce local", "Moutiergue", "Niourouni"],
    yield_potential_t_ha: 1.5,
    notes: "Céréale de soudure par excellence, sans gluten, à forte digestibilité et très faible indice glycémique.",
    iconName: "wheat",
  },
  {
    id: "sheet-ble",
    crop_key: "ble",
    name_fr: "Blé irrigué (Triticum aestivum)",
    category: "Céréales",
    cycle_days_min: 90,
    cycle_days_max: 115,
    climate_zones: ["Boucle du Mouhoun (Sourou)", "Centre-Est (Bagré)"],
    seasons: ["Contre-saison froide (Novembre - Février)"],
    npk_needs: { N: 120, P: 60, K: 60 },
    water_needs_mm: 450,
    common_pests: ["Pucerons des céréales", "Criquets"],
    common_diseases: ["Rouille brune", "Oïdium", "Fusariose de l'épi"],
    recommended_varieties: ["Giza 168", "Sids 1", "Misr 1"],
    yield_potential_t_ha: 4.5,
    notes: "Exige des nuits fraîches (< 18°C) pour le tallage et la floraison. Culture stratégique de substitution aux importations.",
    iconName: "wheat",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 2. LÉGUMINEUSES & PROTÉAGINEUX
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "sheet-niebe",
    crop_key: "niebe",
    name_fr: "Niébé / Haricot (Vigna unguiculata)",
    category: "Légumineuses",
    cycle_days_min: 60,
    cycle_days_max: 85,
    climate_zones: ["Sahel", "Soudano-sahélien", "Soudanien"],
    seasons: ["Hivernage", "Contre-saison maraîchère"],
    npk_needs: { N: 15, P: 40, K: 30 },
    water_needs_mm: 300,
    common_pests: ["Thrips des fleurs (Megalurothrips sjostedti)", "Maruca vitrata", "Pucerons (Aphis craccivora)", "Bruchus en stockage"],
    common_diseases: ["Mosaïque du niébé (CYMV)", "Anthracnose", "Flétrissement fusarien", "Striga gesnerioides"],
    recommended_varieties: ["KVx 399-05", "Komcallé", "Tiligré", "Yiisyandé", "KVx 745-11P", "B301"],
    yield_potential_t_ha: 2.2,
    notes: "Fixe l'azote atmosphérique (réduit les besoins azotés des cultures suivantes). Surveillance phytosanitaire rigoureuse à la floraison.",
    iconName: "sprout",
  },
  {
    id: "sheet-arachide",
    crop_key: "arachide",
    name_fr: "Arachide (Arachis hypogaea)",
    category: "Légumineuses",
    cycle_days_min: 90,
    cycle_days_max: 120,
    climate_zones: ["Soudano-sahélien", "Soudanien", "Guinéen"],
    seasons: ["Hivernage"],
    npk_needs: { N: 20, P: 50, K: 40 },
    water_needs_mm: 450,
    common_pests: ["Iules (mille-pattes)", "Termites", "Pucerons vecteurs de la rosette"],
    common_diseases: ["Rosette de l'arachide", "Cercosporiose précoce et tardive", "Aspergillus flavus (aflatoxines)"],
    recommended_varieties: ["SH 470 P", "RMP 12", "Fleur 11", "QH 243 C"],
    yield_potential_t_ha: 3.0,
    notes: "Nécessite un sol meuble et bien drainé pour la pénétration des gynophores. Séchage rapide au champ indispensable contre les moisissures.",
    iconName: "sprout",
  },
  {
    id: "sheet-voandzou",
    crop_key: "voandzou",
    name_fr: "Voandzou / Pois de terre (Vigna subterranea)",
    category: "Légumineuses",
    cycle_days_min: 95,
    cycle_days_max: 130,
    climate_zones: ["Plateau-Central", "Centre-Nord", "Nord", "Centre-Sud"],
    seasons: ["Hivernage"],
    npk_needs: { N: 15, P: 40, K: 30 },
    water_needs_mm: 380,
    common_pests: ["Bruches des graines", "Nématodes gallicoles", "Punaises"],
    common_diseases: ["Cercosporiose du voandzou", "Pourriture des gousses (Sclerotium)"],
    recommended_varieties: ["Voandzou local blanc", "Voandzou rouge de Manga", "Koudougou local"],
    yield_potential_t_ha: 2.0,
    notes: "Légumineuse vivrière de sécurité très nutritive, tolérant les sols sableux marginaux peu fertiles.",
    iconName: "sprout",
  },
  {
    id: "sheet-soja",
    crop_key: "soja",
    name_fr: "Soja (Glycine max)",
    category: "Légumineuses",
    cycle_days_min: 95,
    cycle_days_max: 125,
    climate_zones: ["Soudanien", "Guinéen"],
    seasons: ["Hivernage"],
    npk_needs: { N: 25, P: 60, K: 50 },
    water_needs_mm: 500,
    common_pests: ["Chenilles défoliatrices", "Punaises vertes phytophages", "Nématodes"],
    common_diseases: ["Rouille asiatique du soja", "Bactériose pustulaire", "Anthracnose"],
    recommended_varieties: ["TGX 1448-2E", "TGX 1904-6F", "Canarana"],
    yield_potential_t_ha: 2.8,
    notes: "Très prisé pour l'alimentation du bétail (tourteaux) et la nutrition humaine. Inoculation par Rhizobium recommandée sur terres vierges.",
    iconName: "sprout",
  },
  {
    id: "sheet-pois-angole",
    crop_key: "pois_angole",
    name_fr: "Pois d'Angole / Pois cajan (Cajanus cajan)",
    category: "Légumineuses",
    cycle_days_min: 120,
    cycle_days_max: 180,
    climate_zones: ["Hauts-Bassins", "Cascades", "Sud-Ouest"],
    seasons: ["Hivernage"],
    npk_needs: { N: 20, P: 40, K: 30 },
    water_needs_mm: 400,
    common_pests: ["Foreurs de gousses (Helicoverpa)", "Bruches"],
    common_diseases: ["Flétrissement fusarien (Fusarium udum)", "Stérilité virale"],
    recommended_varieties: ["ICP 8863", "Variété locale Hauts-Bassins"],
    yield_potential_t_ha: 2.0,
    notes: "Arbuste pérenne d'agroforesterie et haie vive fixateur d'azote profond. Feuilles utilisables comme fourrage riche.",
    iconName: "sprout",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 3. TUBERCULES, RACINES & BULBES
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "sheet-igname",
    crop_key: "igname",
    name_fr: "Igname (Dioscorea alata / rotundata)",
    category: "Tubercules & racines",
    cycle_days_min: 180,
    cycle_days_max: 270,
    climate_zones: ["Passoré", "Sud-Ouest", "Centre-Sud (Pô)", "Liptako"],
    seasons: ["Hivernage (plantation en buttes dès mars-mai)"],
    npk_needs: { N: 80, P: 60, K: 120 },
    water_needs_mm: 900,
    common_pests: ["Nématodes des galles", "Coléoptères des tubercules (Heteroligus)", "Cochenilles"],
    common_diseases: ["Anthracnose de l'igname (Colletotrichum gloeosporioides)", "Virose de la mosaïque (YMV)"],
    recommended_varieties: ["Kponan", "Florido", "Bêtê-bêtê", "Igname de Passoré"],
    yield_potential_t_ha: 25.0,
    notes: "Nécessite de grosses buttes profondes et un tuteurage soigné. Spécialité reconnue du Passoré et du Sud burkinabè.",
    iconName: "sprout",
  },
  {
    id: "sheet-manioc",
    crop_key: "manioc",
    name_fr: "Manioc (Manihot esculenta)",
    category: "Tubercules & racines",
    cycle_days_min: 270,
    cycle_days_max: 360,
    climate_zones: ["Hauts-Bassins", "Cascades", "Sud-Ouest", "Centre-Ouest"],
    seasons: ["Pluviale et pérenne"],
    npk_needs: { N: 60, P: 40, K: 100 },
    water_needs_mm: 700,
    common_pests: ["Cochenille du manioc (Phenacoccus manihoti)", "Acarien vert (Mononychellus tanajoa)"],
    common_diseases: ["Mosaïque africaine du manioc (CMD)", "Bactériose vasculaire (Xanthomonas)", "Striure brune (CBSD)"],
    recommended_varieties: ["Sika", "V99", "TMS 30572", "Manioc doux local"],
    yield_potential_t_ha: 30.0,
    notes: "Bouturage incliné à 45°. Très robuste face aux sécheresses prolongées grâce à ses réserves tubéreuses.",
    iconName: "sprout",
  },
  {
    id: "sheet-patate-douce",
    crop_key: "patate_douce",
    name_fr: "Patate douce (Ipomoea batatas)",
    category: "Tubercules & racines",
    cycle_days_min: 90,
    cycle_days_max: 125,
    climate_zones: ["Hauts-Bassins", "Boucle du Mouhoun", "Centre-Ouest", "Cascades"],
    seasons: ["Hivernage", "Contre-saison irriguée"],
    npk_needs: { N: 50, P: 40, K: 90 },
    water_needs_mm: 450,
    common_pests: ["Charançon de la patate douce (Cylas formicarius)", "Chenilles défoliatrices"],
    common_diseases: ["Complexe viral de la patate douce (SPVD)", "Gale de la patate douce"],
    recommended_varieties: ["BF59", "Tiébélé", "CIP 199062", "Chair orange riche en vitamine A"],
    yield_potential_t_ha: 22.0,
    notes: "Culture rapide, couvre-sol efficace limitant l'érosion et l'enherbement. Feuilles consommables comme légume.",
    iconName: "sprout",
  },
  {
    id: "sheet-pomme-de-terre",
    crop_key: "pomme_de_terre",
    name_fr: "Pomme de terre (Solanum tuberosum)",
    category: "Tubercules & racines",
    cycle_days_min: 80,
    cycle_days_max: 110,
    climate_zones: ["Nord (Ouahigouya, Titao)", "Hauts-Bassins"],
    seasons: ["Contre-saison fraîche (Novembre à Février)"],
    npk_needs: { N: 120, P: 80, K: 150 },
    water_needs_mm: 500,
    common_pests: ["Teigne de la pomme de terre (Phthorimaea operculella)", "Pucerons", "Nématodes"],
    common_diseases: ["Mildiou (Phytophthora infestans)", "Flétrissement bactérien (Ralstonia solanacearum)", "Gale commune"],
    recommended_varieties: ["Sahel", "Spunta", "Aïda", "Claustar"],
    yield_potential_t_ha: 28.0,
    notes: "Filière maraîchère d'excellence de la région du Nord (Titao, Ouahigouya). Buttage régulier obligatoire.",
    iconName: "sprout",
  },
  {
    id: "sheet-taro",
    crop_key: "taro",
    name_fr: "Taro / Macabo (Colocasia esculenta)",
    category: "Tubercules & racines",
    cycle_days_min: 210,
    cycle_days_max: 300,
    climate_zones: ["Cascades", "Sud-Ouest", "Bas-fonds humides"],
    seasons: ["Hivernage en zone humide"],
    npk_needs: { N: 80, P: 50, K: 100 },
    water_needs_mm: 1000,
    common_pests: ["Pucerons du taro", "Vers blancs des racines"],
    common_diseases: ["Mildiou foliaire du taro (Phytophthora colocasiae)", "Pourriture molle des cormes"],
    recommended_varieties: ["Taro violet local", "Taro blanc de Banfora"],
    yield_potential_t_ha: 20.0,
    notes: "Préfère les sols riches en matière organique et constamment humides. Cuisson complète obligatoire pour éliminer les oxalates.",
    iconName: "sprout",
  },
  {
    id: "sheet-souchet",
    crop_key: "souchet",
    name_fr: "Souchet doux / Chufa (Cyperus esculentus)",
    category: "Tubercules & racines",
    cycle_days_min: 95,
    cycle_days_max: 120,
    climate_zones: ["Cascades", "Hauts-Bassins", "Sud-Ouest"],
    seasons: ["Hivernage"],
    npk_needs: { N: 40, P: 30, K: 50 },
    water_needs_mm: 450,
    common_pests: ["Nématodes des racines", "Rongeurs"],
    common_diseases: ["Rouille du souchet", "Pourriture des tubercules"],
    recommended_varieties: ["Gros souchet jaune", "Souchet noir local"],
    yield_potential_t_ha: 4.0,
    notes: "Petits tubercules sucrés très recherchés pour la confection de farines et de boissons lactées végétales (Horchata).",
    iconName: "sprout",
  },
  {
    id: "sheet-gingembre",
    crop_key: "gingembre",
    name_fr: "Gingembre (Zingiber officinale)",
    category: "Tubercules & racines",
    cycle_days_min: 210,
    cycle_days_max: 270,
    climate_zones: ["Cascades", "Hauts-Bassins", "Sud-Ouest"],
    seasons: ["Hivernage sous microclimat ombragé"],
    npk_needs: { N: 90, P: 60, K: 120 },
    water_needs_mm: 800,
    common_pests: ["Foreurs de tiges", "Nématodes phytophages"],
    common_diseases: ["Pourriture molle bactérienne (Pythium / Ralstonia)", "Flétrissement fusarien"],
    recommended_varieties: ["Gingembre jaune local", "Variété améliorée Comoé"],
    yield_potential_t_ha: 18.0,
    notes: "Rhizome aromatique à forte rentabilité. Exige un paillage abondant et une humidité constante sans engorgement.",
    iconName: "sprout",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 4. CULTURES DE RENTE, INDUSTRIELLES & FIBRES
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "sheet-coton",
    crop_key: "coton",
    name_fr: "Coton conventionnel & biologique (Gossypium hirsutum)",
    category: "Cultures de rente",
    cycle_days_min: 130,
    cycle_days_max: 160,
    climate_zones: ["Soudanien", "Soudano-sahélien", "Boucle du Mouhoun", "Hauts-Bassins"],
    seasons: ["Hivernage"],
    npk_needs: { N: 80, P: 40, K: 60 },
    water_needs_mm: 650,
    common_pests: ["Chenille de la capsule (Helicoverpa armigera)", "Earias", "Mouche blanche (Bemisia tabaci)", "Jassides (Amrasca)"],
    common_diseases: ["Bactériose du cotonnier (Xanthomonas)", "Flétrissement fusarien", "Virose bleue"],
    recommended_varieties: ["FK 37", "FK 64", "STAM 59 A"],
    yield_potential_t_ha: 2.8,
    notes: "Programme de protection phytosanitaire raisonné (fenêtres CAR). Première filière agro-industrielle burkinabè (SOFITEX, SOCOMA, FASOCOTON).",
    iconName: "sprout",
  },
  {
    id: "sheet-sesame",
    crop_key: "sesame",
    name_fr: "Sésame blanc / noir (Sesamum indicum)",
    category: "Cultures de rente",
    cycle_days_min: 80,
    cycle_days_max: 105,
    climate_zones: ["Sahel", "Soudano-sahélien", "Soudanien"],
    seasons: ["Hivernage (semis mi-juillet)"],
    npk_needs: { N: 40, P: 30, K: 20 },
    water_needs_mm: 350,
    common_pests: ["Chenille tordeuse (Antigastra catalaunalis)", "Pucerons", "Criquets"],
    common_diseases: ["Phyllodie (phytoplasme)", "Bactériose", "Cercosporiose"],
    recommended_varieties: ["S-42", "Gimbi", "Humera", "Kola"],
    yield_potential_t_ha: 1.3,
    notes: "Culture piège excellente pour la germination suicide du Striga. Forte valeur à l'exportation vers l'Asie et l'Europe.",
    iconName: "wheat",
  },
  {
    id: "sheet-anacarde",
    crop_key: "anacarde",
    name_fr: "Anacardier / Noix de cajou (Anacardium occidentale)",
    category: "Cultures de rente",
    cycle_days_min: 365,
    cycle_days_max: 365,
    climate_zones: ["Cascades", "Sud-Ouest", "Hauts-Bassins"],
    seasons: ["Pérenne (récolte Février - Mai)"],
    npk_needs: { N: 60, P: 40, K: 80 },
    water_needs_mm: 800,
    common_pests: ["Punaise thrips (Helopeltis)", "Foreur des branches (Apate terebrans)", "Charançon de l'anacarde"],
    common_diseases: ["Anthracnose de l'anacardier (Colletotrichum)", "Gommose bactérienne"],
    recommended_varieties: ["Clones INERA greffés à haut rendement", "Variétés locales sélectionnées"],
    yield_potential_t_ha: 2.0,
    notes: "Deuxième produit agricole d'exportation du Burkina Faso. Élagage d'aération et ramassage régulier au sol indispensables.",
    iconName: "sprout",
  },
  {
    id: "sheet-karite",
    crop_key: "karite",
    name_fr: "Karité (Vitellaria paradoxa)",
    category: "Cultures de rente",
    cycle_days_min: 365,
    cycle_days_max: 365,
    climate_zones: ["Toutes régions hors Sahel extrême"],
    seasons: ["Pérenne (fructification Mai - Août)"],
    npk_needs: { N: 30, P: 20, K: 30 },
    water_needs_mm: 600,
    common_pests: ["Loranthacées (plantes parasites du houppier)", "Chenilles défoliatrices Cirina butyrospermi (chitoumou)"],
    common_diseases: ["Taches foliaires fongiques"],
    recommended_varieties: ["Arbres élites de parcs agroforestiers"],
    yield_potential_t_ha: 1.5,
    notes: "L'or blanc des femmes burkinabè. Les chenilles Cirina (chitoumou) constituent également une ressource protéique très prisée.",
    iconName: "sprout",
  },
  {
    id: "sheet-canne-a-sucre",
    crop_key: "canne_a_sucre",
    name_fr: "Canne à sucre (Saccharum officinarum)",
    category: "Cultures de rente",
    cycle_days_min: 300,
    cycle_days_max: 365,
    climate_zones: ["Cascades (Bérégadougou, Comoé)"],
    seasons: ["Culture irriguée industrielle"],
    npk_needs: { N: 150, P: 70, K: 180 },
    water_needs_mm: 1400,
    common_pests: ["Foreurs de canne (Eldana saccharina)", "Termites"],
    common_diseases: ["Charbon de la canne (Sporisorium)", "Mosaïque de la canne", "Rouille orangée"],
    recommended_varieties: ["R570", "M124/57", "Co997"],
    yield_potential_t_ha: 110.0,
    notes: "Filière agro-industrielle majeure de la SN-SOSUCO à Bérégadougou. Nécessite une maîtrise hydraulique totale par aspersion ou submersion.",
    iconName: "sprout",
  },
  {
    id: "sheet-hibiscus",
    crop_key: "hibiscus",
    name_fr: "Oseille de Guinée / Bissap (Hibiscus sabdariffa)",
    category: "Cultures de rente",
    cycle_days_min: 120,
    cycle_days_max: 150,
    climate_zones: ["Centre", "Centre-Nord", "Plateau-Central", "Nord", "Est"],
    seasons: ["Hivernage"],
    npk_needs: { N: 40, P: 30, K: 40 },
    water_needs_mm: 400,
    common_pests: ["Altises des feuilles", "Punaises des capsules"],
    common_diseases: ["Oïdium", "Flétrissement fusarien", "Anthracnose"],
    recommended_varieties: ["Bissap rouge foncé Vimto", "Bissap blanc local"],
    yield_potential_t_ha: 1.5,
    notes: "Calices séchés très demandés pour les boissons rafraîchissantes et l'exportation agro-alimentaire et pharmaceutique.",
    iconName: "sprout",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 5. MARAÎCHAGE & LÉGUMES DE PLEIN CHAMP
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "sheet-tomate",
    crop_key: "tomate",
    name_fr: "Tomate maraîchère (Solanum lycopersicum)",
    category: "Maraîchage",
    cycle_days_min: 75,
    cycle_days_max: 110,
    climate_zones: ["Soudanien", "Soudano-sahélien", "Périmètres irrigués"],
    seasons: ["Contre-saison fraîche (Oct - Fév)", "Contre-saison chaude"],
    npk_needs: { N: 150, P: 80, K: 180 },
    water_needs_mm: 600,
    common_pests: ["Tuta absoluta (mineuse de la tomate)", "Mouche blanche (Bemisia)", "Nématodes gallicoles", "Noctuelles"],
    common_diseases: ["Mildiou (Phytophthora infestans)", "Flétrissement bactérien (Ralstonia)", "Virus TYLCV (feuilles jaunes en cuillère)"],
    recommended_varieties: ["Mongal F1", "Nirouz F1", "Cobra F1", "Tropimech", "Petomech"],
    yield_potential_t_ha: 45.0,
    notes: "Pépinière soignée sous voile anti-insectes indispensable. Tuteurage et paillage fortement recommandés pour préserver la qualité des fruits.",
    iconName: "sprout",
  },
  {
    id: "sheet-oignon",
    crop_key: "oignon",
    name_fr: "Oignon violet / blanc (Allium cepa)",
    category: "Maraîchage",
    cycle_days_min: 90,
    cycle_days_max: 130,
    climate_zones: ["Soudano-sahélien", "Soudanien", "Vallées & barrages"],
    seasons: ["Contre-saison fraîche"],
    npk_needs: { N: 100, P: 60, K: 120 },
    water_needs_mm: 450,
    common_pests: ["Thrips du tabac et de l'oignon (Thrips tabaci)", "Mouche de l'oignon", "Nématodes"],
    common_diseases: ["Pourriture molle bactérienne", "Tache pourpre (Alternaria porri)", "Fonte des semis"],
    recommended_varieties: ["Violet de Galmi", "Goudami", "Prema F1", "Orient F1"],
    yield_potential_t_ha: 35.0,
    notes: "Arrêt strict de l'irrigation 10 à 15 jours avant la récolte pour assurer un ressuyage optimal et prolonger la conservation en magasin ventilé.",
    iconName: "sprout",
  },
  {
    id: "sheet-chou",
    crop_key: "chou",
    name_fr: "Chou pommé (Brassica oleracea var. capitata)",
    category: "Maraîchage",
    cycle_days_min: 70,
    cycle_days_max: 95,
    climate_zones: ["Centre", "Hauts-Bassins", "Nord", "Boucle du Mouhoun"],
    seasons: ["Contre-saison fraîche"],
    npk_needs: { N: 120, P: 60, K: 120 },
    water_needs_mm: 480,
    common_pests: ["Teigne des crucifères (Plutella xylostella)", "Pucerons cendrés", "Chenille arpenteuse"],
    common_diseases: ["Nervation noire (Xanthomonas campestris)", "Fonte des semis", "Alternariose"],
    recommended_varieties: ["KK Cross F1", "Tropicana F1", "Oxylus F1"],
    yield_potential_t_ha: 38.0,
    notes: "Protection renforcée par bio-insecticides (Bacillus thuringiensis / neem) contre la teigne.",
    iconName: "sprout",
  },
  {
    id: "sheet-gombo",
    crop_key: "gombo",
    name_fr: "Gombo (Abelmoschus esculentus)",
    category: "Maraîchage",
    cycle_days_min: 50,
    cycle_days_max: 90,
    climate_zones: ["Sahel", "Soudano-sahélien", "Soudanien", "Guinéen"],
    seasons: ["Hivernage", "Contre-saison irriguée"],
    npk_needs: { N: 60, P: 40, K: 50 },
    water_needs_mm: 400,
    common_pests: ["Altises des feuilles", "Vers de la capsule (Earias)", "Pucerons"],
    common_diseases: ["Oïdium des cucurbitacées et malvacées", "Enroulement des feuilles (Virose OELCV)"],
    recommended_varieties: ["Clemson Spineless", "Indiana", "Hire", "Sabourou"],
    yield_potential_t_ha: 15.0,
    notes: "Récolte continue tous les 2 à 3 jours pour stimuler la floraison et éviter la lignification des gousses. Haute valeur marchande locale.",
    iconName: "sprout",
  },
  {
    id: "sheet-aubergine-locale",
    crop_key: "aubergine_africaine",
    name_fr: "Aubergine africaine / Djatou (Solanum aethiopicum)",
    category: "Maraîchage",
    cycle_days_min: 75,
    cycle_days_max: 110,
    climate_zones: ["Toutes régions"],
    seasons: ["Hivernage et contre-saison"],
    npk_needs: { N: 80, P: 50, K: 90 },
    water_needs_mm: 450,
    common_pests: ["Acariens rouges", "Punaises phytophages", "Nématodes"],
    common_diseases: ["Anthracnose des fruits", "Flétrissement bactérien (Ralstonia)"],
    recommended_varieties: ["Soxna", "Gilo local", "Kumba"],
    yield_potential_t_ha: 20.0,
    notes: "Légume traditionnel incontournable des sauces locales, plus résistant aux aléas climatiques que l'aubergine violette.",
    iconName: "sprout",
  },
  {
    id: "sheet-piment",
    crop_key: "piment",
    name_fr: "Piment fort & Poivron (Capsicum spp.)",
    category: "Maraîchage",
    cycle_days_min: 80,
    cycle_days_max: 120,
    climate_zones: ["Hauts-Bassins", "Cascades", "Centre", "Nord"],
    seasons: ["Contre-saison et pluviale"],
    npk_needs: { N: 100, P: 60, K: 120 },
    water_needs_mm: 500,
    common_pests: ["Thrips", "Acariens blancs (Polyphagotarsonemus)", "Mouche des fruits"],
    common_diseases: ["Anthracnose du piment", "Virus de la marbrure du piment (PMMV)", "Flétrissement bactérien"],
    recommended_varieties: ["Safsaf", "Big Sun", "Bec d'oiseau local", "Yolo Wonder (poivron)"],
    yield_potential_t_ha: 18.0,
    notes: "Sensible aux écarts thermiques brutaux. Paillage indispensable pour maintenir l'humidité racinaire.",
    iconName: "sprout",
  },
  {
    id: "sheet-carotte",
    crop_key: "carotte",
    name_fr: "Carotte (Daucus carota)",
    category: "Maraîchage",
    cycle_days_min: 75,
    cycle_days_max: 100,
    climate_zones: ["Nord (Ouahigouya)", "Centre", "Hauts-Bassins"],
    seasons: ["Contre-saison fraîche"],
    npk_needs: { N: 80, P: 60, K: 140 },
    water_needs_mm: 400,
    common_pests: ["Mouche de la carotte", "Nématodes à galles (racines fourchues)"],
    common_diseases: ["Alternariose foliaire (Alternaria dauci)", "Oïdium"],
    recommended_varieties: ["New Kuroda", "Nantaise améliorée", "Amazonia"],
    yield_potential_t_ha: 28.0,
    notes: "Exige un sol léger sans cailloux préalablement ameubli pour éviter le fourchement des racines pivotantes.",
    iconName: "sprout",
  },
  {
    id: "sheet-laitue",
    crop_key: "laitue",
    name_fr: "Laitue / Salade (Lactuca sativa)",
    category: "Maraîchage",
    cycle_days_min: 35,
    cycle_days_max: 55,
    climate_zones: ["Ceintures vertes urbaines (Ouaga, Bobo, Koudougou)"],
    seasons: ["Toute l'année sous ombrage et arrosage régulier"],
    npk_needs: { N: 60, P: 30, K: 70 },
    water_needs_mm: 300,
    common_pests: ["Noctuelles défoliatrices", "Pucerons de la laitue", "Limaces"],
    common_diseases: ["Pourriture grise (Botrytis)", "Brûlure de la bordure des feuilles", "Bactériose"],
    recommended_varieties: ["Eden", "Blonde de Paris", "Grand Rapids"],
    yield_potential_t_ha: 20.0,
    notes: "Cycle ultra-court garantissant un cash-flow hebdomadaire rapide aux maraîchers périurbains.",
    iconName: "sprout",
  },
  {
    id: "sheet-pasteque",
    crop_key: "pasteque",
    name_fr: "Pastèque maraîchère (Citrullus lanatus)",
    category: "Maraîchage",
    cycle_days_min: 75,
    cycle_days_max: 95,
    climate_zones: ["Boucle du Mouhoun", "Centre", "Nord", "Hauts-Bassins"],
    seasons: ["Contre-saison chaude (Février - Mai)"],
    npk_needs: { N: 90, P: 60, K: 120 },
    water_needs_mm: 450,
    common_pests: ["Mouche des cucurbitacées (Bactrocera cucurbitae)", "Pucerons", "Criquets"],
    common_diseases: ["Oïdium des cucurbitacées", "Anthracnose", "Fusariose vasculaire"],
    recommended_varieties: ["Kaolack", "Crimson Sweet", "Sugar Baby"],
    yield_potential_t_ha: 40.0,
    notes: "Forte demande lors de la saison chaude et des périodes de jeûne. Paillage plastique et pollinisation active essentiels.",
    iconName: "sprout",
  },
  {
    id: "sheet-haricot-vert",
    crop_key: "haricot_vert",
    name_fr: "Haricot vert filet (Phaseolus vulgaris)",
    category: "Maraîchage",
    cycle_days_min: 50,
    cycle_days_max: 70,
    climate_zones: ["Centre (Koubri)", "Boucle du Mouhoun", "Nord"],
    seasons: ["Contre-saison fraîche (Novembre - Février)"],
    npk_needs: { N: 60, P: 50, K: 80 },
    water_needs_mm: 350,
    common_pests: ["Mouche des semis", "Pucerons noirs", "Thrips"],
    common_diseases: ["Rouille du haricot", "Anthracnose", "Graisse bactérienne"],
    recommended_varieties: ["Alhambra", "Contender", "Paulista"],
    yield_potential_t_ha: 12.0,
    notes: "Culture d'exportation maraîchère par fret aérien vers l'Europe durant l'hiver boréal.",
    iconName: "sprout",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 6. ARBORICULTURE FRUITIÈRE
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "sheet-mangue",
    crop_key: "mangue",
    name_fr: "Manguier (Mangifera indica)",
    category: "Fruits",
    cycle_days_min: 365,
    cycle_days_max: 365,
    climate_zones: ["Hauts-Bassins (Orodara)", "Cascades (Banfora)", "Sud-Ouest"],
    seasons: ["Pérenne (récolte Mars - Juillet)"],
    npk_needs: { N: 80, P: 40, K: 120 },
    water_needs_mm: 750,
    common_pests: ["Mouche des fruits (Bactrocera dorsalis / Ceratitis)", "Cochenille blanche du manguier", "Charançon du noyau"],
    common_diseases: ["Anthracnose de la mangue (Colletotrichum)", "Bactériose du manguier (Xanthomonas)"],
    recommended_varieties: ["Amélie (précoce)", "Kent (export)", "Brooks (tardive)", "Keitt", "Lippens"],
    yield_potential_t_ha: 15.0,
    notes: "Vergers d'exportation majeurs du Sud-Ouest et des Hauts-Bassins. Traitement obligatoire par piégeage paraphéromonal contre la mouche des fruits.",
    iconName: "sprout",
  },
  {
    id: "sheet-banane",
    crop_key: "banane",
    name_fr: "Bananier doux & Plantain (Musa spp.)",
    category: "Fruits",
    cycle_days_min: 270,
    cycle_days_max: 365,
    climate_zones: ["Cascades", "Hauts-Bassins", "Périmètres irrigués du Sud"],
    seasons: ["Pérenne sous irrigation permanente"],
    npk_needs: { N: 180, P: 60, K: 250 },
    water_needs_mm: 1200,
    common_pests: ["Charançon noir du bananier (Cosmopolites sordidus)", "Nématodes des racines (Radopholus)"],
    common_diseases: ["Cercosporiose noire (Mycosphaerella fijiensis)", "Maladie de Panama (Fusarium oxysporum)", "Bunchy top (BBTV)"],
    recommended_varieties: ["Grande Naine", "Williams", "Plantain Corne", "French Sombre"],
    yield_potential_t_ha: 35.0,
    notes: "Exige d'énormes quantités de matière organique et de potasse. Haubanage des régimes nécessaire pour éviter le déracinement.",
    iconName: "sprout",
  },
  {
    id: "sheet-papaye",
    crop_key: "papaye",
    name_fr: "Papayer (Carica papaya)",
    category: "Fruits",
    cycle_days_min: 240,
    cycle_days_max: 365,
    climate_zones: ["Hauts-Bassins", "Cascades", "Centre"],
    seasons: ["Pérenne irriguée"],
    npk_needs: { N: 120, P: 60, K: 150 },
    water_needs_mm: 900,
    common_pests: ["Cochenilles farineuses", "Acariens", "Mouche des fruits"],
    common_diseases: ["Virose des taches en anneaux du papayer (PRSV)", "Pourriture des racines (Phytophthora)"],
    recommended_varieties: ["Solo", "Red Lady F1", "Sunrise"],
    yield_potential_t_ha: 40.0,
    notes: "Entrée en production très rapide (8-9 mois après repiquage). Déteste les sols compacts asphyxiants.",
    iconName: "sprout",
  },
  {
    id: "sheet-agrumes",
    crop_key: "agrumes",
    name_fr: "Agrumes : Citronnier & Oranger (Citrus spp.)",
    category: "Fruits",
    cycle_days_min: 365,
    cycle_days_max: 365,
    climate_zones: ["Hauts-Bassins", "Cascades", "Centre-Sud"],
    seasons: ["Pérenne"],
    npk_needs: { N: 100, P: 50, K: 120 },
    water_needs_mm: 850,
    common_pests: ["Mineuse des feuilles d'agrumes (Phyllocnistis citrella)", "Pucerons noirs", "Cochenilles"],
    common_diseases: ["Gommose à Phytophthora", "Chancre citrique bactérien", "Tristeza des agrumes"],
    recommended_varieties: ["Citron vert de Guinée", "Valencia Late", "Mandarine de Loumbila"],
    yield_potential_t_ha: 22.0,
    notes: "Greffage sur porte-greffe résistant (Citrange Carrizo ou Bigaradier) impératif contre la gommose.",
    iconName: "sprout",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 7. CULTURES FOURRAGÈRES & PASTORALES
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "sheet-niebe-fourrager",
    crop_key: "niebe_fourrager",
    name_fr: "Niébé fourrager (Vigna unguiculata)",
    category: "Fourrages",
    cycle_days_min: 55,
    cycle_days_max: 75,
    climate_zones: ["Toutes zones agro-écologiques"],
    seasons: ["Hivernage"],
    npk_needs: { N: 15, P: 30, K: 20 },
    water_needs_mm: 280,
    common_pests: ["Chenilles défoliatrices", "Pucerons"],
    common_diseases: ["Anthracnose foliaire"],
    recommended_varieties: ["KVx 745-11P", "Variété fourragère INERA"],
    yield_potential_t_ha: 4.5,
    notes: "Production massive de fanes à haute valeur nutritive pour l'embouche bovine et ovine en saison sèche.",
    iconName: "sprout",
  },
  {
    id: "sheet-brachiaria",
    crop_key: "brachiaria",
    name_fr: "Brachiaria (Brachiaria ruziziensis)",
    category: "Fourrages",
    cycle_days_min: 60,
    cycle_days_max: 180,
    climate_zones: ["Hauts-Bassins", "Cascades", "Centre-Sud"],
    seasons: ["Hivernage et contre-saison"],
    npk_needs: { N: 80, P: 40, K: 40 },
    water_needs_mm: 600,
    common_pests: ["Criquets", "Chenilles légionnaires"],
    common_diseases: ["Helminthosporiose"],
    recommended_varieties: ["Brachiaria Ruziziensis", "Brachiaria Hybrid Mulato II"],
    yield_potential_t_ha: 14.0,
    notes: "Graminée pérenne exceptionnelle pour l'ensilage, le foin et le pâturage direct. Améliore la structure du sol.",
    iconName: "wheat",
  },
  {
    id: "sheet-mucuna",
    crop_key: "mucuna",
    name_fr: "Mucuna / Pois mascate (Mucuna pruriens)",
    category: "Fourrages",
    cycle_days_min: 90,
    cycle_days_max: 140,
    climate_zones: ["Hauts-Bassins", "Boucle du Mouhoun", "Cascades"],
    seasons: ["Hivernage"],
    npk_needs: { N: 10, P: 30, K: 20 },
    water_needs_mm: 400,
    common_pests: ["Nématodes (action nématicide naturelle remarquable)"],
    common_diseases: ["Taches foliaires mineures"],
    recommended_varieties: ["Mucuna utilis non urticant"],
    yield_potential_t_ha: 6.0,
    notes: "Plante de couverture étouffant les mauvaises herbes (y compris Cyperus) et enrichissant le sol en azote organique.",
    iconName: "sprout",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 8. PLANTES AROMATIQUES & MÉDICINALES
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "sheet-moringa",
    crop_key: "moringa",
    name_fr: "Moringa / Arbre de vie (Moringa oleifera)",
    category: "Aromatiques & Médicinales",
    cycle_days_min: 60,
    cycle_days_max: 180,
    climate_zones: ["Toutes régions"],
    seasons: ["Toute l'année"],
    npk_needs: { N: 50, P: 30, K: 50 },
    water_needs_mm: 350,
    common_pests: ["Chenilles défoliatrices (Noctuelles)", "Pucerons"],
    common_diseases: ["Pourriture racinaire en sol asphyxiant"],
    recommended_varieties: ["Moringa local CNSF"],
    yield_potential_t_ha: 8.0,
    notes: "Croissance ultra-rapide. Feuilles riches en vitamines et minéraux, graines pour la purification d'eau et l'huile cosmétique.",
    iconName: "sprout",
  },
  {
    id: "sheet-artemisia",
    crop_key: "artemisia",
    name_fr: "Artemisia (Artemisia annua)",
    category: "Aromatiques & Médicinales",
    cycle_days_min: 90,
    cycle_days_max: 150,
    climate_zones: ["Hauts-Bassins", "Plateau-Central", "Cascades"],
    seasons: ["Hivernage et contre-saison fraîche"],
    npk_needs: { N: 60, P: 40, K: 60 },
    water_needs_mm: 500,
    common_pests: ["Pucerons", "Acariens"],
    common_diseases: ["Fonte des semis", "Oïdium"],
    recommended_varieties: ["Artemisia annua sélection locale"],
    yield_potential_t_ha: 3.5,
    notes: "Plante médicinale antipaludique reconnue, séchée sous ombrage pour préserver les principes actifs (artémisinine).",
    iconName: "sprout",
  },
];

// Rétrocompatibilité avec les 12 cultures initiales
export const WEST_AFRICA_12_CROPS = BURKINA_ALL_CROPS_TECHNICAL_SHEETS;
